package com.trisysit.epc_android.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ATTENDANCE_TABLE.
 */
public class AttendanceTable {

    private String id;
    private String name;
    private String date;
    private String inTime;
    private String inGPS;
    private String outTime;
    private String outGPS;
    private String status;
    private String createdDate;
    private String createdBy;
    private String updatedDate;
    private String comment;
    private String updatedBy;
    private String mobileId;
    private String image1;
    private String image2;
    private String image3;
    private String image4;
    private String image5;
    private String image6;

    public AttendanceTable() {
    }

    public AttendanceTable(String mobileId) {
        this.mobileId = mobileId;
    }

    public AttendanceTable(String id, String name, String date, String inTime, String inGPS, String outTime, String outGPS, String status, String createdDate, String createdBy, String updatedDate, String comment, String updatedBy, String mobileId, String image1, String image2, String image3, String image4, String image5, String image6) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.inTime = inTime;
        this.inGPS = inGPS;
        this.outTime = outTime;
        this.outGPS = outGPS;
        this.status = status;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updatedDate = updatedDate;
        this.comment = comment;
        this.updatedBy = updatedBy;
        this.mobileId = mobileId;
        this.image1 = image1;
        this.image2 = image2;
        this.image3 = image3;
        this.image4 = image4;
        this.image5 = image5;
        this.image6 = image6;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getInTime() {
        return inTime;
    }

    public void setInTime(String inTime) {
        this.inTime = inTime;
    }

    public String getInGPS() {
        return inGPS;
    }

    public void setInGPS(String inGPS) {
        this.inGPS = inGPS;
    }

    public String getOutTime() {
        return outTime;
    }

    public void setOutTime(String outTime) {
        this.outTime = outTime;
    }

    public String getOutGPS() {
        return outGPS;
    }

    public void setOutGPS(String outGPS) {
        this.outGPS = outGPS;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(String updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getMobileId() {
        return mobileId;
    }

    public void setMobileId(String mobileId) {
        this.mobileId = mobileId;
    }

    public String getImage1() {
        return image1;
    }

    public void setImage1(String image1) {
        this.image1 = image1;
    }

    public String getImage2() {
        return image2;
    }

    public void setImage2(String image2) {
        this.image2 = image2;
    }

    public String getImage3() {
        return image3;
    }

    public void setImage3(String image3) {
        this.image3 = image3;
    }

    public String getImage4() {
        return image4;
    }

    public void setImage4(String image4) {
        this.image4 = image4;
    }

    public String getImage5() {
        return image5;
    }

    public void setImage5(String image5) {
        this.image5 = image5;
    }

    public String getImage6() {
        return image6;
    }

    public void setImage6(String image6) {
        this.image6 = image6;
    }

}
