package com.trisysit.epc_android.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.trisysit.epc_android.database.AttendanceTable;

import com.trisysit.epc_android.database.AttendanceTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceTableDaoConfig;

    private final AttendanceTableDao attendanceTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceTableDaoConfig = daoConfigMap.get(AttendanceTableDao.class).clone();
        attendanceTableDaoConfig.initIdentityScope(type);

        attendanceTableDao = new AttendanceTableDao(attendanceTableDaoConfig, this);

        registerDao(AttendanceTable.class, attendanceTableDao);
    }
    
    public void clear() {
        attendanceTableDaoConfig.getIdentityScope().clear();
    }

    public AttendanceTableDao getAttendanceTableDao() {
        return attendanceTableDao;
    }

}
