package com.trisysit.epc_android.SqliteDatabase;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 8): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 8;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        DailyUpdateMasterDao.createTable(db, ifNotExists);
        MaterialTableDao.createTable(db, ifNotExists);
        ProjectTaskDao.createTable(db, ifNotExists);
        UserMasterDao.createTable(db, ifNotExists);
        ImageSyncDao.createTable(db, ifNotExists);
        SubActivityMasterDao.createTable(db, ifNotExists);
        ProjectTableDao.createTable(db, ifNotExists);
        TasktableDao.createTable(db, ifNotExists);
        LocationMasterDao.createTable(db, ifNotExists);
        ActivityMasterDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        DailyUpdateMasterDao.dropTable(db, ifExists);
        MaterialTableDao.dropTable(db, ifExists);
        ProjectTaskDao.dropTable(db, ifExists);
        UserMasterDao.dropTable(db, ifExists);
        ImageSyncDao.dropTable(db, ifExists);
        SubActivityMasterDao.dropTable(db, ifExists);
        ProjectTableDao.dropTable(db, ifExists);
        TasktableDao.dropTable(db, ifExists);
        LocationMasterDao.dropTable(db, ifExists);
        ActivityMasterDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DailyUpdateMasterDao.class);
        registerDaoClass(MaterialTableDao.class);
        registerDaoClass(ProjectTaskDao.class);
        registerDaoClass(UserMasterDao.class);
        registerDaoClass(ImageSyncDao.class);
        registerDaoClass(SubActivityMasterDao.class);
        registerDaoClass(ProjectTableDao.class);
        registerDaoClass(TasktableDao.class);
        registerDaoClass(LocationMasterDao.class);
        registerDaoClass(ActivityMasterDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
