package com.trisysit.epc_android.SqliteDatabase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.trisysit.epc_android.SqliteDatabase.DailyUpdateMaster;
import com.trisysit.epc_android.SqliteDatabase.MaterialTable;
import com.trisysit.epc_android.SqliteDatabase.ProjectTask;
import com.trisysit.epc_android.SqliteDatabase.UserMaster;
import com.trisysit.epc_android.SqliteDatabase.ImageSync;
import com.trisysit.epc_android.SqliteDatabase.SubActivityMaster;
import com.trisysit.epc_android.SqliteDatabase.ProjectTable;
import com.trisysit.epc_android.SqliteDatabase.Tasktable;
import com.trisysit.epc_android.SqliteDatabase.LocationMaster;
import com.trisysit.epc_android.SqliteDatabase.ActivityMaster;

import com.trisysit.epc_android.SqliteDatabase.DailyUpdateMasterDao;
import com.trisysit.epc_android.SqliteDatabase.MaterialTableDao;
import com.trisysit.epc_android.SqliteDatabase.ProjectTaskDao;
import com.trisysit.epc_android.SqliteDatabase.UserMasterDao;
import com.trisysit.epc_android.SqliteDatabase.ImageSyncDao;
import com.trisysit.epc_android.SqliteDatabase.SubActivityMasterDao;
import com.trisysit.epc_android.SqliteDatabase.ProjectTableDao;
import com.trisysit.epc_android.SqliteDatabase.TasktableDao;
import com.trisysit.epc_android.SqliteDatabase.LocationMasterDao;
import com.trisysit.epc_android.SqliteDatabase.ActivityMasterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyUpdateMasterDaoConfig;
    private final DaoConfig materialTableDaoConfig;
    private final DaoConfig projectTaskDaoConfig;
    private final DaoConfig userMasterDaoConfig;
    private final DaoConfig imageSyncDaoConfig;
    private final DaoConfig subActivityMasterDaoConfig;
    private final DaoConfig projectTableDaoConfig;
    private final DaoConfig tasktableDaoConfig;
    private final DaoConfig locationMasterDaoConfig;
    private final DaoConfig activityMasterDaoConfig;

    private final DailyUpdateMasterDao dailyUpdateMasterDao;
    private final MaterialTableDao materialTableDao;
    private final ProjectTaskDao projectTaskDao;
    private final UserMasterDao userMasterDao;
    private final ImageSyncDao imageSyncDao;
    private final SubActivityMasterDao subActivityMasterDao;
    private final ProjectTableDao projectTableDao;
    private final TasktableDao tasktableDao;
    private final LocationMasterDao locationMasterDao;
    private final ActivityMasterDao activityMasterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyUpdateMasterDaoConfig = daoConfigMap.get(DailyUpdateMasterDao.class).clone();
        dailyUpdateMasterDaoConfig.initIdentityScope(type);

        materialTableDaoConfig = daoConfigMap.get(MaterialTableDao.class).clone();
        materialTableDaoConfig.initIdentityScope(type);

        projectTaskDaoConfig = daoConfigMap.get(ProjectTaskDao.class).clone();
        projectTaskDaoConfig.initIdentityScope(type);

        userMasterDaoConfig = daoConfigMap.get(UserMasterDao.class).clone();
        userMasterDaoConfig.initIdentityScope(type);

        imageSyncDaoConfig = daoConfigMap.get(ImageSyncDao.class).clone();
        imageSyncDaoConfig.initIdentityScope(type);

        subActivityMasterDaoConfig = daoConfigMap.get(SubActivityMasterDao.class).clone();
        subActivityMasterDaoConfig.initIdentityScope(type);

        projectTableDaoConfig = daoConfigMap.get(ProjectTableDao.class).clone();
        projectTableDaoConfig.initIdentityScope(type);

        tasktableDaoConfig = daoConfigMap.get(TasktableDao.class).clone();
        tasktableDaoConfig.initIdentityScope(type);

        locationMasterDaoConfig = daoConfigMap.get(LocationMasterDao.class).clone();
        locationMasterDaoConfig.initIdentityScope(type);

        activityMasterDaoConfig = daoConfigMap.get(ActivityMasterDao.class).clone();
        activityMasterDaoConfig.initIdentityScope(type);

        dailyUpdateMasterDao = new DailyUpdateMasterDao(dailyUpdateMasterDaoConfig, this);
        materialTableDao = new MaterialTableDao(materialTableDaoConfig, this);
        projectTaskDao = new ProjectTaskDao(projectTaskDaoConfig, this);
        userMasterDao = new UserMasterDao(userMasterDaoConfig, this);
        imageSyncDao = new ImageSyncDao(imageSyncDaoConfig, this);
        subActivityMasterDao = new SubActivityMasterDao(subActivityMasterDaoConfig, this);
        projectTableDao = new ProjectTableDao(projectTableDaoConfig, this);
        tasktableDao = new TasktableDao(tasktableDaoConfig, this);
        locationMasterDao = new LocationMasterDao(locationMasterDaoConfig, this);
        activityMasterDao = new ActivityMasterDao(activityMasterDaoConfig, this);

        registerDao(DailyUpdateMaster.class, dailyUpdateMasterDao);
        registerDao(MaterialTable.class, materialTableDao);
        registerDao(ProjectTask.class, projectTaskDao);
        registerDao(UserMaster.class, userMasterDao);
        registerDao(ImageSync.class, imageSyncDao);
        registerDao(SubActivityMaster.class, subActivityMasterDao);
        registerDao(ProjectTable.class, projectTableDao);
        registerDao(Tasktable.class, tasktableDao);
        registerDao(LocationMaster.class, locationMasterDao);
        registerDao(ActivityMaster.class, activityMasterDao);
    }
    
    public void clear() {
        dailyUpdateMasterDaoConfig.clearIdentityScope();
        materialTableDaoConfig.clearIdentityScope();
        projectTaskDaoConfig.clearIdentityScope();
        userMasterDaoConfig.clearIdentityScope();
        imageSyncDaoConfig.clearIdentityScope();
        subActivityMasterDaoConfig.clearIdentityScope();
        projectTableDaoConfig.clearIdentityScope();
        tasktableDaoConfig.clearIdentityScope();
        locationMasterDaoConfig.clearIdentityScope();
        activityMasterDaoConfig.clearIdentityScope();
    }

    public DailyUpdateMasterDao getDailyUpdateMasterDao() {
        return dailyUpdateMasterDao;
    }

    public MaterialTableDao getMaterialTableDao() {
        return materialTableDao;
    }

    public ProjectTaskDao getProjectTaskDao() {
        return projectTaskDao;
    }

    public UserMasterDao getUserMasterDao() {
        return userMasterDao;
    }

    public ImageSyncDao getImageSyncDao() {
        return imageSyncDao;
    }

    public SubActivityMasterDao getSubActivityMasterDao() {
        return subActivityMasterDao;
    }

    public ProjectTableDao getProjectTableDao() {
        return projectTableDao;
    }

    public TasktableDao getTasktableDao() {
        return tasktableDao;
    }

    public LocationMasterDao getLocationMasterDao() {
        return locationMasterDao;
    }

    public ActivityMasterDao getActivityMasterDao() {
        return activityMasterDao;
    }

}
