package com.trisysit.epc_android.SqliteDatabase;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASKTABLE".
*/
public class TasktableDao extends AbstractDao<Tasktable, String> {

    public static final String TABLENAME = "TASKTABLE";

    /**
     * Properties of entity Tasktable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TaskId = new Property(0, String.class, "taskId", true, "TASK_ID");
        public final static Property Comment = new Property(1, String.class, "comment", false, "COMMENT");
        public final static Property Priority = new Property(2, String.class, "priority", false, "PRIORITY");
        public final static Property ReminderText = new Property(3, String.class, "reminderText", false, "REMINDER_TEXT");
        public final static Property ReminderUrl = new Property(4, String.class, "reminderUrl", false, "REMINDER_URL");
        public final static Property ManPowerReq = new Property(5, String.class, "manPowerReq", false, "MAN_POWER_REQ");
        public final static Property ActualManPowerReq = new Property(6, String.class, "actualManPowerReq", false, "ACTUAL_MAN_POWER_REQ");
        public final static Property PercentComplete = new Property(7, String.class, "percentComplete", false, "PERCENT_COMPLETE");
        public final static Property Subject = new Property(8, String.class, "subject", false, "SUBJECT");
        public final static Property Material_count = new Property(9, Integer.class, "material_count", false, "MATERIAL_COUNT");
        public final static Property TaskCreatedDate = new Property(10, String.class, "taskCreatedDate", false, "TASK_CREATED_DATE");
        public final static Property TaskFor = new Property(11, String.class, "taskFor", false, "TASK_FOR");
        public final static Property TaskStatus = new Property(12, String.class, "taskStatus", false, "TASK_STATUS");
        public final static Property TaskUpdatedDate = new Property(13, String.class, "taskUpdatedDate", false, "TASK_UPDATED_DATE");
        public final static Property AssignedTo = new Property(14, String.class, "assignedTo", false, "ASSIGNED_TO");
        public final static Property AssignedToName = new Property(15, String.class, "assignedToName", false, "ASSIGNED_TO_NAME");
        public final static Property TaskCreatedBy = new Property(16, String.class, "taskCreatedBy", false, "TASK_CREATED_BY");
        public final static Property TaskUpdatedBy = new Property(17, String.class, "taskUpdatedBy", false, "TASK_UPDATED_BY");
        public final static Property TaskStartDate = new Property(18, String.class, "taskStartDate", false, "TASK_START_DATE");
        public final static Property TaskEndDate = new Property(19, String.class, "taskEndDate", false, "TASK_END_DATE");
        public final static Property TaskEffort = new Property(20, String.class, "taskEffort", false, "TASK_EFFORT");
        public final static Property TaskActualStartDate = new Property(21, String.class, "taskActualStartDate", false, "TASK_ACTUAL_START_DATE");
        public final static Property TaskActualEndDate = new Property(22, String.class, "taskActualEndDate", false, "TASK_ACTUAL_END_DATE");
        public final static Property TaskActualEffort = new Property(23, String.class, "taskActualEffort", false, "TASK_ACTUAL_EFFORT");
        public final static Property ParentTaskId = new Property(24, String.class, "parentTaskId", false, "PARENT_TASK_ID");
        public final static Property PredecessorTaskId = new Property(25, String.class, "predecessorTaskId", false, "PREDECESSOR_TASK_ID");
        public final static Property ProjectId = new Property(26, String.class, "projectId", false, "PROJECT_ID");
        public final static Property Critical = new Property(27, Boolean.class, "critical", false, "CRITICAL");
        public final static Property Section = new Property(28, String.class, "section", false, "SECTION");
        public final static Property IsTrackable = new Property(29, Boolean.class, "isTrackable", false, "IS_TRACKABLE");
        public final static Property IsWorkSchedule = new Property(30, Boolean.class, "isWorkSchedule", false, "IS_WORK_SCHEDULE");
        public final static Property Duration = new Property(31, String.class, "duration", false, "DURATION");
        public final static Property SubTaskCount = new Property(32, Integer.class, "subTaskCount", false, "SUB_TASK_COUNT");
        public final static Property Variance = new Property(33, Integer.class, "variance", false, "VARIANCE");
        public final static Property UserDetails = new Property(34, String.class, "userDetails", false, "USER_DETAILS");
        public final static Property TaskStartDateNew = new Property(35, String.class, "taskStartDateNew", false, "TASK_START_DATE_NEW");
        public final static Property Unit = new Property(36, String.class, "unit", false, "UNIT");
        public final static Property Loa = new Property(37, String.class, "loa", false, "LOA");
        public final static Property ActualLoa = new Property(38, String.class, "actualLoa", false, "ACTUAL_LOA");
        public final static Property Schedule = new Property(39, String.class, "schedule", false, "SCHEDULE");
        public final static Property Description = new Property(40, String.class, "description", false, "DESCRIPTION");
        public final static Property OrderBy = new Property(41, String.class, "orderBy", false, "ORDER_BY");
    }


    public TasktableDao(DaoConfig config) {
        super(config);
    }
    
    public TasktableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASKTABLE\" (" + //
                "\"TASK_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: taskId
                "\"COMMENT\" TEXT," + // 1: comment
                "\"PRIORITY\" TEXT," + // 2: priority
                "\"REMINDER_TEXT\" TEXT," + // 3: reminderText
                "\"REMINDER_URL\" TEXT," + // 4: reminderUrl
                "\"MAN_POWER_REQ\" TEXT," + // 5: manPowerReq
                "\"ACTUAL_MAN_POWER_REQ\" TEXT," + // 6: actualManPowerReq
                "\"PERCENT_COMPLETE\" TEXT," + // 7: percentComplete
                "\"SUBJECT\" TEXT," + // 8: subject
                "\"MATERIAL_COUNT\" INTEGER," + // 9: material_count
                "\"TASK_CREATED_DATE\" TEXT," + // 10: taskCreatedDate
                "\"TASK_FOR\" TEXT," + // 11: taskFor
                "\"TASK_STATUS\" TEXT," + // 12: taskStatus
                "\"TASK_UPDATED_DATE\" TEXT," + // 13: taskUpdatedDate
                "\"ASSIGNED_TO\" TEXT," + // 14: assignedTo
                "\"ASSIGNED_TO_NAME\" TEXT," + // 15: assignedToName
                "\"TASK_CREATED_BY\" TEXT," + // 16: taskCreatedBy
                "\"TASK_UPDATED_BY\" TEXT," + // 17: taskUpdatedBy
                "\"TASK_START_DATE\" TEXT," + // 18: taskStartDate
                "\"TASK_END_DATE\" TEXT," + // 19: taskEndDate
                "\"TASK_EFFORT\" TEXT," + // 20: taskEffort
                "\"TASK_ACTUAL_START_DATE\" TEXT," + // 21: taskActualStartDate
                "\"TASK_ACTUAL_END_DATE\" TEXT," + // 22: taskActualEndDate
                "\"TASK_ACTUAL_EFFORT\" TEXT," + // 23: taskActualEffort
                "\"PARENT_TASK_ID\" TEXT," + // 24: parentTaskId
                "\"PREDECESSOR_TASK_ID\" TEXT," + // 25: predecessorTaskId
                "\"PROJECT_ID\" TEXT," + // 26: projectId
                "\"CRITICAL\" INTEGER," + // 27: critical
                "\"SECTION\" TEXT," + // 28: section
                "\"IS_TRACKABLE\" INTEGER," + // 29: isTrackable
                "\"IS_WORK_SCHEDULE\" INTEGER," + // 30: isWorkSchedule
                "\"DURATION\" TEXT," + // 31: duration
                "\"SUB_TASK_COUNT\" INTEGER," + // 32: subTaskCount
                "\"VARIANCE\" INTEGER," + // 33: variance
                "\"USER_DETAILS\" TEXT," + // 34: userDetails
                "\"TASK_START_DATE_NEW\" TEXT," + // 35: taskStartDateNew
                "\"UNIT\" TEXT," + // 36: unit
                "\"LOA\" TEXT," + // 37: loa
                "\"ACTUAL_LOA\" TEXT," + // 38: actualLoa
                "\"SCHEDULE\" TEXT," + // 39: schedule
                "\"DESCRIPTION\" TEXT," + // 40: description
                "\"ORDER_BY\" TEXT);"); // 41: orderBy
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASKTABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Tasktable entity) {
        stmt.clearBindings();
 
        String taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindString(1, taskId);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(2, comment);
        }
 
        String priority = entity.getPriority();
        if (priority != null) {
            stmt.bindString(3, priority);
        }
 
        String reminderText = entity.getReminderText();
        if (reminderText != null) {
            stmt.bindString(4, reminderText);
        }
 
        String reminderUrl = entity.getReminderUrl();
        if (reminderUrl != null) {
            stmt.bindString(5, reminderUrl);
        }
 
        String manPowerReq = entity.getManPowerReq();
        if (manPowerReq != null) {
            stmt.bindString(6, manPowerReq);
        }
 
        String actualManPowerReq = entity.getActualManPowerReq();
        if (actualManPowerReq != null) {
            stmt.bindString(7, actualManPowerReq);
        }
 
        String percentComplete = entity.getPercentComplete();
        if (percentComplete != null) {
            stmt.bindString(8, percentComplete);
        }
 
        String subject = entity.getSubject();
        if (subject != null) {
            stmt.bindString(9, subject);
        }
 
        Integer material_count = entity.getMaterial_count();
        if (material_count != null) {
            stmt.bindLong(10, material_count);
        }
 
        String taskCreatedDate = entity.getTaskCreatedDate();
        if (taskCreatedDate != null) {
            stmt.bindString(11, taskCreatedDate);
        }
 
        String taskFor = entity.getTaskFor();
        if (taskFor != null) {
            stmt.bindString(12, taskFor);
        }
 
        String taskStatus = entity.getTaskStatus();
        if (taskStatus != null) {
            stmt.bindString(13, taskStatus);
        }
 
        String taskUpdatedDate = entity.getTaskUpdatedDate();
        if (taskUpdatedDate != null) {
            stmt.bindString(14, taskUpdatedDate);
        }
 
        String assignedTo = entity.getAssignedTo();
        if (assignedTo != null) {
            stmt.bindString(15, assignedTo);
        }
 
        String assignedToName = entity.getAssignedToName();
        if (assignedToName != null) {
            stmt.bindString(16, assignedToName);
        }
 
        String taskCreatedBy = entity.getTaskCreatedBy();
        if (taskCreatedBy != null) {
            stmt.bindString(17, taskCreatedBy);
        }
 
        String taskUpdatedBy = entity.getTaskUpdatedBy();
        if (taskUpdatedBy != null) {
            stmt.bindString(18, taskUpdatedBy);
        }
 
        String taskStartDate = entity.getTaskStartDate();
        if (taskStartDate != null) {
            stmt.bindString(19, taskStartDate);
        }
 
        String taskEndDate = entity.getTaskEndDate();
        if (taskEndDate != null) {
            stmt.bindString(20, taskEndDate);
        }
 
        String taskEffort = entity.getTaskEffort();
        if (taskEffort != null) {
            stmt.bindString(21, taskEffort);
        }
 
        String taskActualStartDate = entity.getTaskActualStartDate();
        if (taskActualStartDate != null) {
            stmt.bindString(22, taskActualStartDate);
        }
 
        String taskActualEndDate = entity.getTaskActualEndDate();
        if (taskActualEndDate != null) {
            stmt.bindString(23, taskActualEndDate);
        }
 
        String taskActualEffort = entity.getTaskActualEffort();
        if (taskActualEffort != null) {
            stmt.bindString(24, taskActualEffort);
        }
 
        String parentTaskId = entity.getParentTaskId();
        if (parentTaskId != null) {
            stmt.bindString(25, parentTaskId);
        }
 
        String predecessorTaskId = entity.getPredecessorTaskId();
        if (predecessorTaskId != null) {
            stmt.bindString(26, predecessorTaskId);
        }
 
        String projectId = entity.getProjectId();
        if (projectId != null) {
            stmt.bindString(27, projectId);
        }
 
        Boolean critical = entity.getCritical();
        if (critical != null) {
            stmt.bindLong(28, critical ? 1L: 0L);
        }
 
        String section = entity.getSection();
        if (section != null) {
            stmt.bindString(29, section);
        }
 
        Boolean isTrackable = entity.getIsTrackable();
        if (isTrackable != null) {
            stmt.bindLong(30, isTrackable ? 1L: 0L);
        }
 
        Boolean isWorkSchedule = entity.getIsWorkSchedule();
        if (isWorkSchedule != null) {
            stmt.bindLong(31, isWorkSchedule ? 1L: 0L);
        }
 
        String duration = entity.getDuration();
        if (duration != null) {
            stmt.bindString(32, duration);
        }
 
        Integer subTaskCount = entity.getSubTaskCount();
        if (subTaskCount != null) {
            stmt.bindLong(33, subTaskCount);
        }
 
        Integer variance = entity.getVariance();
        if (variance != null) {
            stmt.bindLong(34, variance);
        }
 
        String userDetails = entity.getUserDetails();
        if (userDetails != null) {
            stmt.bindString(35, userDetails);
        }
 
        String taskStartDateNew = entity.getTaskStartDateNew();
        if (taskStartDateNew != null) {
            stmt.bindString(36, taskStartDateNew);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(37, unit);
        }
 
        String loa = entity.getLoa();
        if (loa != null) {
            stmt.bindString(38, loa);
        }
 
        String actualLoa = entity.getActualLoa();
        if (actualLoa != null) {
            stmt.bindString(39, actualLoa);
        }
 
        String schedule = entity.getSchedule();
        if (schedule != null) {
            stmt.bindString(40, schedule);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(41, description);
        }
 
        String orderBy = entity.getOrderBy();
        if (orderBy != null) {
            stmt.bindString(42, orderBy);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Tasktable entity) {
        stmt.clearBindings();
 
        String taskId = entity.getTaskId();
        if (taskId != null) {
            stmt.bindString(1, taskId);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(2, comment);
        }
 
        String priority = entity.getPriority();
        if (priority != null) {
            stmt.bindString(3, priority);
        }
 
        String reminderText = entity.getReminderText();
        if (reminderText != null) {
            stmt.bindString(4, reminderText);
        }
 
        String reminderUrl = entity.getReminderUrl();
        if (reminderUrl != null) {
            stmt.bindString(5, reminderUrl);
        }
 
        String manPowerReq = entity.getManPowerReq();
        if (manPowerReq != null) {
            stmt.bindString(6, manPowerReq);
        }
 
        String actualManPowerReq = entity.getActualManPowerReq();
        if (actualManPowerReq != null) {
            stmt.bindString(7, actualManPowerReq);
        }
 
        String percentComplete = entity.getPercentComplete();
        if (percentComplete != null) {
            stmt.bindString(8, percentComplete);
        }
 
        String subject = entity.getSubject();
        if (subject != null) {
            stmt.bindString(9, subject);
        }
 
        Integer material_count = entity.getMaterial_count();
        if (material_count != null) {
            stmt.bindLong(10, material_count);
        }
 
        String taskCreatedDate = entity.getTaskCreatedDate();
        if (taskCreatedDate != null) {
            stmt.bindString(11, taskCreatedDate);
        }
 
        String taskFor = entity.getTaskFor();
        if (taskFor != null) {
            stmt.bindString(12, taskFor);
        }
 
        String taskStatus = entity.getTaskStatus();
        if (taskStatus != null) {
            stmt.bindString(13, taskStatus);
        }
 
        String taskUpdatedDate = entity.getTaskUpdatedDate();
        if (taskUpdatedDate != null) {
            stmt.bindString(14, taskUpdatedDate);
        }
 
        String assignedTo = entity.getAssignedTo();
        if (assignedTo != null) {
            stmt.bindString(15, assignedTo);
        }
 
        String assignedToName = entity.getAssignedToName();
        if (assignedToName != null) {
            stmt.bindString(16, assignedToName);
        }
 
        String taskCreatedBy = entity.getTaskCreatedBy();
        if (taskCreatedBy != null) {
            stmt.bindString(17, taskCreatedBy);
        }
 
        String taskUpdatedBy = entity.getTaskUpdatedBy();
        if (taskUpdatedBy != null) {
            stmt.bindString(18, taskUpdatedBy);
        }
 
        String taskStartDate = entity.getTaskStartDate();
        if (taskStartDate != null) {
            stmt.bindString(19, taskStartDate);
        }
 
        String taskEndDate = entity.getTaskEndDate();
        if (taskEndDate != null) {
            stmt.bindString(20, taskEndDate);
        }
 
        String taskEffort = entity.getTaskEffort();
        if (taskEffort != null) {
            stmt.bindString(21, taskEffort);
        }
 
        String taskActualStartDate = entity.getTaskActualStartDate();
        if (taskActualStartDate != null) {
            stmt.bindString(22, taskActualStartDate);
        }
 
        String taskActualEndDate = entity.getTaskActualEndDate();
        if (taskActualEndDate != null) {
            stmt.bindString(23, taskActualEndDate);
        }
 
        String taskActualEffort = entity.getTaskActualEffort();
        if (taskActualEffort != null) {
            stmt.bindString(24, taskActualEffort);
        }
 
        String parentTaskId = entity.getParentTaskId();
        if (parentTaskId != null) {
            stmt.bindString(25, parentTaskId);
        }
 
        String predecessorTaskId = entity.getPredecessorTaskId();
        if (predecessorTaskId != null) {
            stmt.bindString(26, predecessorTaskId);
        }
 
        String projectId = entity.getProjectId();
        if (projectId != null) {
            stmt.bindString(27, projectId);
        }
 
        Boolean critical = entity.getCritical();
        if (critical != null) {
            stmt.bindLong(28, critical ? 1L: 0L);
        }
 
        String section = entity.getSection();
        if (section != null) {
            stmt.bindString(29, section);
        }
 
        Boolean isTrackable = entity.getIsTrackable();
        if (isTrackable != null) {
            stmt.bindLong(30, isTrackable ? 1L: 0L);
        }
 
        Boolean isWorkSchedule = entity.getIsWorkSchedule();
        if (isWorkSchedule != null) {
            stmt.bindLong(31, isWorkSchedule ? 1L: 0L);
        }
 
        String duration = entity.getDuration();
        if (duration != null) {
            stmt.bindString(32, duration);
        }
 
        Integer subTaskCount = entity.getSubTaskCount();
        if (subTaskCount != null) {
            stmt.bindLong(33, subTaskCount);
        }
 
        Integer variance = entity.getVariance();
        if (variance != null) {
            stmt.bindLong(34, variance);
        }
 
        String userDetails = entity.getUserDetails();
        if (userDetails != null) {
            stmt.bindString(35, userDetails);
        }
 
        String taskStartDateNew = entity.getTaskStartDateNew();
        if (taskStartDateNew != null) {
            stmt.bindString(36, taskStartDateNew);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(37, unit);
        }
 
        String loa = entity.getLoa();
        if (loa != null) {
            stmt.bindString(38, loa);
        }
 
        String actualLoa = entity.getActualLoa();
        if (actualLoa != null) {
            stmt.bindString(39, actualLoa);
        }
 
        String schedule = entity.getSchedule();
        if (schedule != null) {
            stmt.bindString(40, schedule);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(41, description);
        }
 
        String orderBy = entity.getOrderBy();
        if (orderBy != null) {
            stmt.bindString(42, orderBy);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Tasktable readEntity(Cursor cursor, int offset) {
        Tasktable entity = new Tasktable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // taskId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // comment
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // priority
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // reminderText
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // reminderUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // manPowerReq
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // actualManPowerReq
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // percentComplete
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // subject
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // material_count
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // taskCreatedDate
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // taskFor
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // taskStatus
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // taskUpdatedDate
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // assignedTo
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // assignedToName
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // taskCreatedBy
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // taskUpdatedBy
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // taskStartDate
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // taskEndDate
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // taskEffort
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // taskActualStartDate
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // taskActualEndDate
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // taskActualEffort
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // parentTaskId
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // predecessorTaskId
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // projectId
            cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0, // critical
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // section
            cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0, // isTrackable
            cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30) != 0, // isWorkSchedule
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // duration
            cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32), // subTaskCount
            cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33), // variance
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // userDetails
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // taskStartDateNew
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // unit
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // loa
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // actualLoa
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // schedule
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // description
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41) // orderBy
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Tasktable entity, int offset) {
        entity.setTaskId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setComment(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPriority(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setReminderText(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setReminderUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setManPowerReq(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setActualManPowerReq(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPercentComplete(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSubject(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setMaterial_count(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setTaskCreatedDate(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTaskFor(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTaskStatus(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTaskUpdatedDate(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAssignedTo(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setAssignedToName(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTaskCreatedBy(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTaskUpdatedBy(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTaskStartDate(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTaskEndDate(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTaskEffort(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTaskActualStartDate(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTaskActualEndDate(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTaskActualEffort(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setParentTaskId(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setPredecessorTaskId(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setProjectId(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setCritical(cursor.isNull(offset + 27) ? null : cursor.getShort(offset + 27) != 0);
        entity.setSection(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setIsTrackable(cursor.isNull(offset + 29) ? null : cursor.getShort(offset + 29) != 0);
        entity.setIsWorkSchedule(cursor.isNull(offset + 30) ? null : cursor.getShort(offset + 30) != 0);
        entity.setDuration(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setSubTaskCount(cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32));
        entity.setVariance(cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33));
        entity.setUserDetails(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setTaskStartDateNew(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setUnit(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setLoa(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setActualLoa(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setSchedule(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setDescription(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setOrderBy(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Tasktable entity, long rowId) {
        return entity.getTaskId();
    }
    
    @Override
    public String getKey(Tasktable entity) {
        if(entity != null) {
            return entity.getTaskId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Tasktable entity) {
        return entity.getTaskId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
